apps/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.user_create, name='user_create'),
    url(r'^verify/$', views.verify, name='verify'),
    url(r'^verify/token/$', views.get_verify_token, name='get_verify_token'),
    url(r'^account/$', views.user_update, name='user_update'),
    url(r'^account/password/$', views.password_change, name='password_change'),
]

apps/minecraft/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^webop/$', views.webop, name='webop'),
    url(r'^webop/spectator/$', views.spectator, name='spectator'),
    url(r'^webop/spectator/go/$', views.gamemode_spectator, name='gamemode_spectator'),
]

apps/shop/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.product_list, name='list'),
    url(r'^product/(?P<pk>\d+)/$', views.product_order, name='product_order'),
    url(r'^myorders/$', views.order_list, name='order_list'),
    url(r'^order/(?P<pk>\d+)/$', views.order_detail, name='order_detail'),
    url(r'^order/(?P<pk>\d+)/redeem/$', views.order_redeem, name='order_redeem'),
]

thefarland/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^accounts/', include('apps.accounts.urls', namespace='accounts')),
    url(r'^board/', include('apps.boards.urls', namespace='boards')),
    url(r'^shop/', include('apps.shop.urls', namespace='shop')),
    url(r'^polls/', include('apps.polls.urls', namespace='polls')),
    url(r'^mc/', include('apps.minecraft.urls', namespace='minecraft')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/_pagination.html
<div class="pagination-centered">
  <ul class="pagination" role="menubar" aria-label="Pagination">
    {% if page_obj.has_previous %}
      <li class="arrow">
        <a href="?page={{ page_obj.previous_page_number }}">&lsaquo; {{ previous }}</a>
      </li>
    {% endif %}

    {% for page in page_obj.pages %}
      {% if page %}
        {% if page == page_obj.number %}
          <li class="current"><a>{{ page }}</a></li>
        {% else %}
        <li>
          <a href="?page={{ page }}">{{ page }}</a>
        </li>
        {% endif %}
      {% else %}
        <li class="unavailable">...</li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="arrow">
        <a href="?page={{ page_obj.next_page_number }}">{{ next }} &raquo;</a>
      </li>
    {% endif %}
  </ul>
</div>

templates/base.html
<!doctype html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
  {% load staticfiles %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>{% block title %}The Farland – Vanilla Minecraft Server{% endblock %}</title>
  <meta name="description" content="Pure vanilla Minecraft Survival Multiplayer Server with twisted terrain. A challenge for experienced players looking for a new adventure.">

  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:700,300">
  <link rel="stylesheet" href="{% static 'bower_components/foundation/css/foundation.css' %}">
  <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'style.css' %}">
  {% block extrahead %}{% endblock %}
</head>
<body>

{% block main %}

  <div class="row">
    <div class="small-4 columns">
      <h1>
        <a href="{% url 'index' %}">The Farland</a>
      </h1>
    </div>
    <div class="small-8 columns">
      <div class="sub-nav user-nav">
        {% if user.is_authenticated %}
          {% if user.is_verified %}
            <img src="{{ user.get_avatar_url }}" width="48" height="48" class="user-avatar">
          {% endif %}
          <div class="user-name">Hello, {{ user.get_short_name }}</div>
          <a href="{% url 'accounts:user_update' %}">My account</a>
          <a class="user-logout" href="{% url 'accounts:logout' %}">Logout</a>
        {% else %}
          Hello, Anonymous<br>
          <a href="{% url 'accounts:login' %}">Login</a>
          <a href="{% url 'accounts:user_create' %}">Register</a>
        {% endif %}
        <div class="clear"></div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="small-12 columns">
      <nav class="top-bar" role="navigation">
        <section class="top-bar-section">
          <ul class="right">
            {% if perms.minecraft.is_op %}
              <li><a href="{% url 'minecraft:webop' %}">WebOp</a></li>
            {% endif %}
          </ul>
          <ul class="left">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'boards:list' %}">Board</a></li>
            <li><a href="{% url 'shop:list' %}">Shop</a></li>
            <li><a href="{% url 'polls:list' %}">Polls</a></li>
            <li><a href="{% url 'contact' %}">Contact</a></li>
          </ul>
        </section>
      </nav>
    </div>
  </div>
  <div class="row">
    <div class="small-12 columns">
      {% if not user.is_anonymous and not user.is_verified %}
        <div class="alert-box warning">
          You haven't verified your username yet. You can participate in raffles and vote with your verified user account!
          <a class="tiny secondary button" href="{% url 'accounts:verify' %}">Verify now!</a>
        </div>
      {% endif %}

      {% for message in messages %}
        <div class="alert-box {{ message.tags }}">{{ message }}</div>
      {% endfor %}

      {% block content %}
        <p>Hello, world!</p>
      {% endblock %}
    </div>
  </div>

{% endblock %}

{% if debug %}
<div class="alert-box secondary">
  <p><strong>SQL Queries</strong></p>
  <ol>
  {% for query in sql_queries %}
  <li>
    <code>{{ query.sql }}</code>
    (in {{ query.time }}s)
  </li>
  {% endfor %}
  </ol>
</div>
{% endif %}

<script src="{% static 'script.js' %}"></script>
<script>
/*jshint -W030 */
(function(i,s,o,g,r,a,m){i.GoogleAnalyticsObject=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments);},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m);
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-55738229-1', 'auto');
ga('require', 'displayfeatures');
ga('send', 'pageview');
</script>

</body>
</html>

templates/contact.html
{% extends "base.html" %}

{% block content %}

  <h2>Contact us</h2>

  <p>Do you have a question for us or want to dispute your ban? Go ahead!</p>

  <p>To ask Reikoartz a.k.a. Angelo a question, send an email to angelo@thefar.land</p>
  <p>Drop a line at julian@thefar.land to have your question answered by hadroncollider a.k.a. Julian.</p>

  <h3><abbr title="Frequently Asked Questions">F.A.Q.</abbr></h3>
  <dl>
    <dt>Is it really 100% Vanilla Minecraft?</dt>
    <dd>Yes, utterly and completely.</dd>

    <dt>.. but how do you do <em>X</em> then?</dt>
    <dd>Command blocks and <code>/scoreboard</code> magic.</dd>

    <dt>Is <em>X</em> allowed on this server?</dt>
    <dd>Read the rules at the spawn temple and use your brain to figure it out.</dd>

    <dt>Can I swear on this server?</dt>
    <dd>Yes, you fucking can swear.</dd>

    <dt>This website sucks.</dt>
    <dd>That's not a question and we're working on it.</dd>
    <dd>In the meantime, check out the screenshots linked above.</dd>
  </dl>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

  <h2>Vanilla Minecraft server with a twist</h2>

  <p>Hey there! The Farland Minecraft server is now open for everybody!</p>
  <p>Feel free to join our server. If you have any questions <a href="{% url 'contact' %}">send us an email</a>.</p>

  <h2>Server Address</h2>
  <p><strong>thefar.land</strong> (enter this in your Minecraft client).</p>

  <h3>Server Rules</h3>
  <ol>
    <li>Don't be a hacker, those kind of people tend to like vanilla flavor.</li>
    <li>Don't be a beggar. You're also not from Planet Minecraft.</li>
    <li>Don't be a cunt. Swearing is allowed but be mature.</li>
  </ol>

  <h3>Support us!</h3>
  <p><a href="http://minecraft-server-list.com/server/262254/vote/" target="_blank">Vote for us here!</a></p>

  <h3>Donations</h3>
  <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
    <input type="hidden" name="cmd" value="_donations">
    <input type="hidden" name="business" value="donations@thefar.land">
    <!-- <input type="hidden" name="lc" value="CH"> -->
    <input type="hidden" name="item_name" value="The Farland Server Upkeep">
    <input type="hidden" name="no_note" value="0">
    <input type="hidden" name="cn" value="Your Minecraft username:">
    <input type="hidden" name="no_shipping" value="1">
    <input type="hidden" name="rm" value="1">
    <input type="hidden" name="return" value="http://thefar.land/">

    <p>Help us pay for the server, donate now.</p>
    <div class="row">
      <div class="small-3 columns">
        <label for="donate_currency">Currency</label>
        <select id="donate_currency" name="currency_code">
          <option value="CHF">CHF</option>
          <option value="USD">US $</option>
          <option value="EUR">€</option>
          <option value="GBP">GB £</option>
          <option value="CAD">CA $</option>
          <option value="AUD">AU $</option>
        </select>
      </div>
      <div class="small-3 columns">
        <label for="donate_amount">Amount</label>
        <input id="donate_amount" type="number" name="amount" value="5.00" min="1.00" max="100.00" step="1.00">
      </div>
      <div class="small-6 columns"></div>
    </div>
    <button type="submit" class="small button">Donate with PayPal</button>
    <small>Swiss Francs (CHF) are preferred to keep the conversion fees low.</small>
  </form>

{% endblock %}

templates/settings.html
{% extends 'base.html' %}

{% block title %}thefar.land | settings{% endblock %}

{% block content %}
<div class="row">
  <div class="large-3 columns">
    <ul class="side-nav">
      <li>
        <a href="{% url 'accounts:user_update' %}">My account</a>
      </li>
      <li>
        <a href="{% url 'shop:order_list' %}">My orders</a>
      </li>
    </ul>
  </div>
  <div class="large-9 columns">
    {% block settings %}{% endblock %}
  </div>
</div>
{% endblock %}